"""inicial

Revision ID: ffc9ab1e2e7d
Revises: 
Create Date: 2025-06-06 09:34:28.373823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc9ab1e2e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=17), nullable=False),
    sa.Column('tipo_plano', sa.String(length=50), nullable=False),
    sa.Column('data_nasc', sa.String(), nullable=False),
    sa.Column('pagamento', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('beneficiarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beneficiarios_id'), ['id'], unique=False)

    op.create_table('dependentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('titular', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['titular'], ['beneficiarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependentes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependentes_id'))

    op.drop_table('dependentes')
    with op.batch_alter_table('beneficiarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiarios_id'))

    op.drop_table('beneficiarios')
    # ### end Alembic commands ###
